str = 'Ayush VaZe'
print(str.upper())
print(str.lower())
print(str.rstrip(''))
print(str.replace('Ayush','Mia'))
print(str.split())
print(str.capitalize())
print(str.count('VaZe'))
print(str.endswith('e'))
print(str.find('Z'))
print(str.find('ss'))
print(str.isalnum())
print(str.isalpha())
print(str.isprintable())
print(str.isspace())
print(str.istitle())